### PR TITLE
add beijing, chengdu and xi'an traj time dataset

### PR DESCRIPTION
**Pull request by PotassiumWings**

### CODE REVIEW

**Comment by PotassiumWings** [comment]
- [ ] finish bj_roadmap_node
- [ ] run scripts, add new rows in readme

**Comment by PotassiumWings** [comment]
@aptx1231 应该是已经跑出来了

**Comment by aptx1231** [comment]
> @aptx1231 应该是已经跑出来了

这几个文件的第一行都应该加入：# link: Please contact the author!

**Comment by PotassiumWings** [comment]
done. @aptx1231

**Pull request merged**
